CREATE DATABASE EXAMEN_FINAL;
USE EXAMEN_FINAL;

CREATE TABLE MEDIO_COMUNICACION(
	 ID_MEDIO INTEGER NOT NULL AUTO_INCREMENT,
     NOMBRE_MEDIO_COMUNICACION VARCHAR(100),
     TIPO_MEDIO_COMUNICACION VARCHAR(1),
     PAIS_ORIGEN VARCHAR(100),
     FECHA_CREACION DATETIME,
     ESTADO TINYINT,
	CONSTRAINT PK_ID_MEDIO PRIMARY KEY(ID_MEDIO)
);
